version: '2'

services:
  users:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/src/app"

  auth:
    build:
      context: .
    ports:
      - "4000:3000"
    volumes:
      - ".:/src/app"
